import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 font-base text-foreground scrollbar scrollbar-thumb-black dark:scrollbar-thumb-white">
        <div className="mx-auto max-w-[700px] px-5">
          {children}
          <Toaster richColors />
        </div>
      </body>
    </html>
  );
}
